### ISSUE TITLE
Superb project! Simply thank you!

### ISSUE THREAD

**Issue by shujaatak** [hash1018/ShCAD#2]
By the way, if you add **topics** below the description of ShCAD description then more people will be able to find your repository and give ShCAD the stars it deserve!
Again thank you for this great project.

**Comment by hash1018** [comment]
hi

**Comment by hash1018** [comment]
Hi First of all, I am new to gitHub and I made this project as a portfolio to get a job. 
I didn't expect that my project would get interests.   I appriciate your comment.

**Comment by shujaatak** [comment]
As much as your repositories get attention so much you will get chances of either hiring or getting projects orders! If you are confident enough then I assure you that you can start your own business :)
If you like working from home then you can try https://www.fiverr.com/, https://www.upwork.com/, https://www.udemy.com/, among others.

**Comment by hash1018** [comment]
Thanks again.  I already got a job , I think this project was really helpful. whenver I interview them, they always asked about ShCAD (in fact I rarely prepared for coding test, etc) .
this project is applied on about 11 Design Pattern (Composite,Visitor,Decorator,State,Strategy,Factory Method .. etc) which prove that I am experties to software architecture.

**Comment by shujaatak** [comment]
That's Fantastic! Good to hear that you have got a job! 
Happy coding!

**Comment by hash1018** [comment]
@shujaatak Hello again.

I want to introduce you my second cad toy-project based on Web  https://github.com/hash1018/ShCAD-web

I'm still developing at the moment and it's written in Rust using Yew, Axum framework.
