### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dongsooHan** [hash1018/ShCAD#5]
Hi, I am Dongsoo Han, CEO of software company in Korea. I found your repo quite interesting since I am looking for a software engineer with CAD development experience. I noticed that you are Korean based on your commit ID name. 

My company is located in Kangnam Korea. If you are interested, please let me know. My contact is dhan at z-emotion.com, 010-4611-6950. 

Thanks,

-Dongsoo

**Comment by hash1018** [comment]
Hello, this is Seungho Ha. 
first of all, Thank you for your offer. I am Junior Software Developer, who just started to work since last year. I don't know if I am the right person you are looking for. ShCAD is the project I developed for hobby. I don't have any 3D experience. It's just based on 2D.

**Comment by hash1018** [comment]
> Hi, I am Dongsoo Han, CEO of software company in Korea. I found your repo quite interesting since I am looking for a software engineer with CAD development experience. I noticed that you are Korean based on your commit ID name.
> 
> My company is located in Kangnam Korea. If you are interested, please let me know. My contact is dhan at z-emotion.com, 010-4611-6950.
> 
> Thanks,
> 
> -Dongsoo
Hello, this is Seungho Ha.
first of all, Thank you for your offer. I am Junior Software Developer, who just started to work since last year. I don't know if I am the right person you are looking for. ShCAD is the project I developed for hobby. I don't have any 3D experience. It's just based on 2D.

**Comment by dongsooHan** [comment]
I am open for wide range of experience level and no 3D is OK. If you are still interested, please feel free  to contact me. As an engineer myself, I always enjoy talking to passionate people like you.

**Comment by hash1018** [comment]
> I am open for wide range of experience level and no 3D is OK. If you are still interested, please feel free to contact me. As an engineer myself, I always enjoy talking to passionate people like you.

I suggest you to meet at cafe just for casual at the beginning I also work in Nambu bus terminal, Seocho

**Comment by dongsooHan** [comment]
Please email or call me when you are available.
